{% set name = "xmitgcm" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 66d427b7ca2d26345695e8e645aa0ea2a86d39cccaf34b68d51cc4d76eaf067d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - xarray >=0.10.1
    - dask >=0.12
    - numpy

test:
  imports:
    - xmitgcm

about:
  home: https://github.com/xgcm/xmitgcm
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
# next release will not need to manually package the license_file
  summary: Read MITgcm mds binary files into xarray
  dev_url: https://github.com/xgcm/xmitgcm
  doc_url: https://xmitgcm.readthedocs.io/

extra:
  recipe-maintainers:
    - raphaeldussin
    - ocefpaf
    - jbusecke
    - rabernat
    - timothyas
