{% set name = "xmitgcm" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7dda45fdf6182a859f5c441cd5928a7c99d41c8bcea9fccf471b7011791b1131

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner
  run:
    - python >=3.7
    - xarray >=0.11
    - dask >=1.0
    - numpy
    - cachetools
    - packaging
    - fsspec
    - zarr

test:
  imports:
    - xmitgcm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mitgcm/xmitgcm
  license: MIT
  license_file: LICENSE
  summary: Read MITgcm mds binary files into xarray
  dev_url: https://github.com/mitgcm/xmitgcm
  doc_url: https://xmitgcm.readthedocs.io/

extra:
  recipe-maintainers:
    - raphaeldussin
    - ocefpaf
    - jbusecke
    - rabernat
    - timothyas
