travis:
  secure:
    BINSTAR_TOKEN: AE4d67+y1bPmiZUNxaivHYs3NcmUGaD2DgR1DwSiI+HwOsdPz89rbPBikJyGjkjfl2QluKsxpF3aaw82qNx5SyISYvPfMVfRaeSLkAz2zzmM+bOd20UygXaYOWIhYRSEw28ap+G5iYUoDGTzhq0kvp/3ABsDlQvoQmmHLcGmXdvuNSuCyvr0vOPTwe6mY4hf9dwxLJrQ7TDwUJIzRESStKE2iPp+6WttVpfZL8NLBoslAHL//MvlgUusxZCLgnplzMyNamAWoyk+m+VoBMaKSau4uAhjQAvqc6zvmIfD9XJDmmngDYUpN0aSC4zT3v2+uA+cAoflYcm6W7tbTUDmXDLnq5lKK8z85XnIYN6i69KaNlBFGRxEgjlWiCg7fluoN+xwlCKKcDf08P/nV30xxua1kFOFKqTyzgpymvNtyPRt0Jg0PM/MvxkVd1PqhDfIdXhhT9iRJ6OWDclXrE729TQO/Fj8ZhZ44hTPMap0Y4XBdhl8OinrYV/AiTI1b3T4WmEyqQwIIRK45s7zob6nw8lgF63fjLciM4nJOt8INyRRBvlLms0nW0zfRFuUL1TadEtpi9WTrlr0xSP5trmStfZl8syFBDXrXXXT+cKYQloo70V8nwuIS6csmQUgV8/8gaHbMn2JHwU5m9HwUUJykuZkaOQlMdAH/BVLLo6hYc4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
