travis:
  secure:
    BINSTAR_TOKEN: fszRVvohciaFDW2aYnCQFffR8PskysVeKSn7UnMTL/6nRZX6WYTe0tDsa8JBe68RlqQCXJQnGqQZlcHr1XUFikwO1XyUTJYRhHmEh3oBIrO5GocvGE+iM9O4bbA8sqbUyRTI2hy42GFOQO1ccXIo8Ua9PguPB183jxK4b4CIO+LTJPX4bCSwxDY/HKDbxWTLtX46lAGbUWeCrVKYjbUyRa/LPIPnh7k4pr8HQDEvjO+9T0PwMGSSu9FEt9o3Rpq7hkqrj/pDAPzHX06RCKuD6eKtAdGnJQfguX2c52yDka0rKLZYQH2wC7q8wXjB9JKemmRsn5Z+oHHgCBY/iUnT4fBVr0Ppp53iE3Pp+KeAH8NFBsvlCfS7P3iA021b3MAdRlH5J53HX+FPfijP7HJ+s2IoGP3+f8fXPcqDloQYe7y+aW1CT7co9vs+vGW1pzPfv72KlMlHA3/IbASneCycR+fQ6gR5oaW9gUruXsQTwv2peB4u1gvzvjozEbve/Kc67z6ykS4RL1VFW1s1Y1JX3mFHnntlMCUIZuuNm84kBii09syaD/qZdnlWoqRqhmT2gaFhlplgMpzTjAhdi0zG1TUuuGUTyf/MpVyXlV3BlxdO8fAYwWyMjWPlOJKeCe632FidIioNLTFpmgeWGOm8EzR9XWFNQ81bqQc1HoogNUU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
