travis:
  secure:
    BINSTAR_TOKEN: u5/X6tSIjyb5f2sHCKVM1+waRv+8PqMfS001BH4QuvX+3Q2uQiybPF3VuuVYzBvklG5to/hllE5I7WO326tOSVcx/GaXQ5v156bRoBCKqxeQTeeLYR3KBmXunbtUJNIEtuMLna07AQWGwfGkIVVaD/ASOk4KF2Zw7hZrnSofaIKfCdk8j0aSczp/RyriHBpWI0esz4czALaHdKVbkYpdEx/HEyBt/x8PKYXY6Xvz+n6D1MF6hXwWTBlyb/HJfGN9hJjVQhQdAqNN0KMzlWFcq0plQuBB/ILsWfZ8fZ88vJnlNHwJ7VVGmsCekiXxD5SMNMu12O6uLjl/PE4d+vglqIUQ+bPh6jx9fTHgNVG+940kW+zB6jloWplG9gnzliMlfo3blsFgnvfjwaV6e7oPm90V5sARpy7SJXNArXGRMiNeXUE1iSAhIJ3XdWa0rasvIA5Qcx7cAapDMmBCV/XN8uHBrUeCTSXH4j23dPaKJrj1i+IVXhz7ei3sKA80TneyLghjjWjvi7ON53sJnLsbqd9j8x5LyH+aPYUs0oxMR1foabJr3h6LZLz2G7WBmkFEHA2bF1C7pR2gec0C5pXvk77CQoQWimwlzELcZ6T5NP7piDnufLX+AK23EcphRBGJkQ5z13bDyrPT1jMGaJIint8zMkjuy1EJARh1WPifwW4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
